Register macros on `register()` to avoid race condition
Normally all routes will be registered during `boot()`, if a package service provider using Inertia get loaded first before `Inertia\ServiceProvider` they will face the following error:

```
InvalidArgumentException: Attribute [inertia] does not exist.
```